# Generated by Django 6.1 on 2026-08-25 11:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('coin', 'Coin')], db_index=True, help_text='Market asset such as gold, silver, or coin.', max_length=20)),
                ('purity', models.PositiveSmallIntegerField(blank=True, help_text='Purity/karat of the asset when applicable. For example, 18 or 24 for gold.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('buy_price', models.DecimalField(decimal_places=2, help_text='Market purchase price.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('sell_price', models.DecimalField(decimal_places=2, help_text='Market selling price.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(choices=[('IRR', 'Iranian Rial')], default='IRR', help_text='Currency of the market prices.', max_length=3)),
                ('provider', models.CharField(choices=[('manual', 'Manual'), ('external_api', 'External API')], db_index=True, default='manual', help_text='Provider that supplied this market price.', max_length=30)),
                ('source', models.CharField(blank=True, default='', help_text='Human-readable source information. For example, an API name or administrative source.', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this market price is currently active.')),
                ('effective_at', models.DateTimeField(db_index=True, help_text='The exact time at which this market price became effective.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_at', '-id'],
                'indexes': [models.Index(fields=['asset', 'purity', '-effective_at'], name='pricing_market_asset_time_idx'), models.Index(fields=['asset', 'is_active', '-effective_at'], name='pricing_market_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('buy_price__gte', 0)), name='market_buy_price_non_negative'), models.CheckConstraint(condition=models.Q(('sell_price__gte', 0)), name='market_sell_price_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_price', models.DecimalField(decimal_places=2, help_text='Market price used during the calculation.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('weight', models.DecimalField(decimal_places=4, help_text='Product weight used for the calculation.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('purity', models.PositiveSmallIntegerField(help_text='Product gold purity/karat at calculation time.', validators=[django.core.validators.MinValueValidator(1)])),
                ('gold_value', models.DecimalField(decimal_places=2, help_text='Base gold value before additional charges.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('making_charge', models.DecimalField(decimal_places=2, help_text='Making fee calculated at the time of pricing.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('profit', models.DecimalField(decimal_places=2, help_text='Seller profit calculated at the time of pricing.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax', models.DecimalField(decimal_places=2, help_text='Tax amount calculated at the time of pricing.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('other_charges', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Other charges included in the final price.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Discount amount applied to the price.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Price before discount.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Final customer price after all adjustments.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(choices=[('IRR', 'Iranian Rial')], default='IRR', max_length=3)),
                ('calculated_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Time at which this price snapshot was created.')),
            ],
            options={
                'ordering': ['-calculated_at', '-id'],
                'indexes': [models.Index(fields=['-calculated_at'], name='pricing_snapshot_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('market_price__gte', 0)), name='snapshot_market_price_non_negative'), models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='snapshot_weight_positive'), models.CheckConstraint(condition=models.Q(('gold_value__gte', 0)), name='snapshot_gold_value_non_negative'), models.CheckConstraint(condition=models.Q(('making_charge__gte', 0)), name='snapshot_making_non_negative'), models.CheckConstraint(condition=models.Q(('profit__gte', 0)), name='snapshot_profit_non_negative'), models.CheckConstraint(condition=models.Q(('tax__gte', 0)), name='snapshot_tax_non_negative'), models.CheckConstraint(condition=models.Q(('other_charges__gte', 0)), name='snapshot_other_charges_non_negative'), models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='snapshot_discount_non_negative'), models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='snapshot_subtotal_non_negative'), models.CheckConstraint(condition=models.Q(('final_price__gte', 0)), name='snapshot_final_price_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique human-readable name for this pricing rule.', max_length=100, unique=True)),
                ('making_fee_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=20)),
                ('making_fee_value', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Making fee value. Percentage or fixed amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('profit_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=20)),
                ('profit_value', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Seller profit value. Percentage or fixed amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Tax rate as a percentage.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('other_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Additional fixed charges.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateTimeField(blank=True, db_index=True, help_text='When this pricing rule becomes effective.', null=True)),
                ('effective_until', models.DateTimeField(blank=True, db_index=True, help_text='When this pricing rule stops being effective.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='pricing_rule_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('making_fee_value__gte', 0)), name='pricing_rule_making_fee_non_negative'), models.CheckConstraint(condition=models.Q(('profit_value__gte', 0)), name='pricing_rule_profit_non_negative'), models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0)), name='pricing_rule_tax_non_negative'), models.CheckConstraint(condition=models.Q(('other_charge__gte', 0)), name='pricing_rule_other_charge_non_negative')],
            },
        ),
    ]
