# Generated by Django 6.0.8 on 2026-09-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pricesnapshot_created_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='marketprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('asset', 'purity'), name='unique_active_market_price_asset_purity'),
        ),
    ]
