from django.conf import settings
from django.db import models


class Notification(models.Model):
    """
    Represents a user notification generated by the system.

    Notifications are stored persistently so users can review
    important events even after the original event has occurred.
    """

    class NotificationType(models.TextChoices):
        ORDER_CREATED = "order_created", "Order Created"
        ORDER_STATUS_CHANGED = "order_status_changed", "Order Status Changed"
        PAYMENT_SUCCESS = "payment_success", "Payment Success"
        PAYMENT_FAILED = "payment_failed", "Payment Failed"
        COUPON_EXPIRING = "coupon_expiring", "Coupon Expiring"
        SYSTEM = "system", "System"

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="notifications",
    )

    notification_type = models.CharField(
        max_length=50,
        choices=NotificationType.choices,
    )

    title = models.CharField(
        max_length=255,
    )

    message = models.TextField()

    is_read = models.BooleanField(
        default=False,
    )

    data = models.JSONField(
        default=dict,
        blank=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    read_at = models.DateTimeField(
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ["-created_at"]

        indexes = [
            models.Index(
                fields=["user", "is_read"],
                name="notification_user_read_idx",
            ),
            models.Index(
                fields=["user", "created_at"],
                name="notification_user_created_idx",
            ),
        ]

    def __str__(self):
        return f"{self.title} - {self.user}"