# Generated by Django 6.1 on 2026-09-17 07:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used.', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('per_user_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times one user can use this coupon.', null=True)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_value__gt', 0)), name='coupon_discount_value_positive'), models.CheckConstraint(condition=models.Q(('minimum_order_amount__gte', 0)), name='coupon_minimum_order_non_negative'), models.CheckConstraint(condition=models.Q(('usage_limit__isnull', True), ('usage_limit__gt', 0), _connector='OR'), name='coupon_usage_limit_positive'), models.CheckConstraint(condition=models.Q(('per_user_limit__isnull', True), ('per_user_limit__gt', 0), _connector='OR'), name='coupon_per_user_limit_positive'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('starts_at'))), name='coupon_expiration_after_start')],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='coupons.coupon')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_usage', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'constraints': [models.UniqueConstraint(fields=('coupon', 'order'), name='unique_coupon_order_usage')],
            },
        ),
    ]
