# Generated by Django 6.1 on 2026-09-15 12:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ پرداخت')),
                ('currency', models.CharField(choices=[('IRR', 'ریال ایران')], default='IRR', max_length=3, verbose_name='واحد پول')),
                ('gateway', models.CharField(choices=[('card_to_card', 'کارت به کارت'), ('zarinpal', 'زرین پال')], db_index=True, default='card_to_card', max_length=30, verbose_name='درگاه پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('processing', 'در حال پردازش'), ('success', 'موفق'), ('failed', 'ناموفق'), ('refunded', 'بازپرداخت شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payments/receipts/%Y/%m/', verbose_name='تصویر فیش واریزی')),
                ('failure_reason', models.TextField(blank=True, verbose_name='دلیل شکست پرداخت')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'ایجاد پرداخت'), ('receipt_uploaded', 'آپلود فیش'), ('processing', 'شروع پردازش'), ('success', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('refund_requested', 'درخواست بازپرداخت'), ('refund_completed', 'بازپرداخت موفق'), ('refund_failed', 'بازپرداخت ناموفق')], db_index=True, max_length=30, verbose_name='رویداد')),
                ('message', models.TextField(blank=True, verbose_name='پیام')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.payment', verbose_name='پرداخت')),
            ],
            options={
                'verbose_name': 'لاگ پرداخت',
                'verbose_name_plural': 'لاگ\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ بازپرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('success', 'موفق'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت بازپرداخت')),
                ('reason', models.TextField(blank=True, verbose_name='دلیل بازپرداخت')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پردازش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='پرداخت')),
            ],
            options={
                'verbose_name': 'بازپرداخت',
                'verbose_name_plural': 'بازپرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', '-created_at'], name='payment_order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payment_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway', 'status'], name='payment_gateway_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['payment', '-created_at'], name='paymentlog_payment_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['event', '-created_at'], name='paymentlog_event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', '-created_at'], name='refund_payment_created_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', '-created_at'], name='refund_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'),
        ),
    ]
