# Generated by Django 6.1 on 2026-09-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'حرکت موجودی', 'verbose_name_plural': 'حرکت\u200cهای موجودی'},
        ),
    ]
