# Generated by Django 6.1 on 2026-09-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wishlistitem',
            name='unique_wishlist_product_variant',
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('wishlist', 'product'), name='unique_wishlist_product_without_variant'),
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('wishlist', 'product', 'variant'), name='unique_wishlist_product_variant'),
        ),
    ]
